### ISSUE TITLE
jumping after enlargement of elements

### ISSUE THREAD

**Issue by fisruk** [metafizzy/isotope#1031]
Hello, 
i try to resize a single item on click like here [http://codepen.io/desandro/pen/scajv] . After enlargement, all items behind resized item jumping arround once more.

[http://codepen.io/anon/pen/WrgbdV]

many thanks for the support in advance

**Comment by desandro** [comment]
Thanks for reporting this issue. This double transition is being caused by CSS transitions. You can resolve this issue by removing this CSS

``` css
.isotope .panel, .isotope-sizer {
  float: left;
  width: 270px;
  -webkit-transition: transform 300ms;
  -o-transition: transform 300ms;
  transition: transform 300ms;
}
```
