### ISSUE TITLE
Element queries for columnWidth element sizing

### ISSUE THREAD

**Issue by mnajafzadeh** [metafizzy/isotope#1105]
Hi,

I can set the number of columns based on screen width but, not the container width!
Do I need to use some plugins like: https://github.com/tysonmatanich/elementQuery/tree/prod

Link to reduced test case:
[http://codepen.io/axentmedia/pen/WwVwNX](http://codepen.io/axentmedia/pen/WwVwNX)

Sometimes the masonry in inside a container but media queries are only for screen.
Is there any solution to resize based on container width like elementQuery stated above?

This is my code:

```html
<table style="width: 100%;">
<tr>
	<td style="width: 30%;"></td>
	<td style="width: 70%;">
<div class="grid">
  <div class="grid-sizer"></div>
  <div class="gutter-sizer"></div>
  <div class="grid-item">1</div>
  <div class="grid-item">2</div>
  <div class="grid-item">3</div>
  <div class="grid-item">4</div>
  <div class="grid-item">5</div>
  <div class="grid-item">6</div>
</div>
    </td>
</tr>
</table>
```

```css
.grid-item {
  float: left;
  height: 100px;
  background: #0D8;
  border-color: hsla(0, 0%, 0%, 0.7);
  margin-bottom: 10px;
}
.gutter-sizer { width: 0.5%; }
.grid-sizer,
.grid-item { width: 19.5%; }

@media (min-width: 960px) and (max-width: 1200px) {
    .grid-sizer,
    .grid-item { width: 24.5%; }
}

@media (min-width: 768px) and (max-width: 959px) {
    .grid-sizer,
    .grid-item { width: 24.5%; }
}

@media (min-width: 600px) and (max-width: 767px) {
    .grid-sizer,
    .grid-item { width: 32.5%; }
}

@media (min-width: 480px) and (max-width: 599px) {
    .grid-sizer,
    .grid-item { width: 49.5%; }
}

@media (min-width: 320px) and (max-width: 479px) {
    .grid-sizer,
    .grid-item { width: 49.5%; }
}

@media (max-width: 319px) {
    .grid-sizer,
    .grid-item { width: 100%; }
}
```

```javascript
$(document).ready(function() {
    var $grid = $('.grid').isotope({
      layoutMode: 'masonry',
      itemSelector: '.grid-item',
      //percentPosition: true,
      masonry: {
        columnWidth: '.grid-sizer',
        gutter: '.gutter-sizer'
      }
    });
});
```
