### ISSUE TITLE
Issue with calc() position in Safari

### ISSUE THREAD

**Issue by rubenbristian** [metafizzy/isotope#1186]
**Test case:** http://codepen.io/rubenbristian/pen/ZBzbZg?editors=1111

Hi

I have an issue with a pretty edge case, don't know if it's something that you can help with, but i wanted to throw this in here.

The main idea is that for a purpose, i want a certain element to stand out and have it's own css position (only left), like a STAMP, but included in the grid. For this purpose, i am giving it a certain width and a certain fixed left position using calc().. Now in my example the calc() is pretty weird, but any calc() breaks the rest javascript code with an error.

Please check out in any browser - you will get a good looking grid and an alert after one second.

This doesn't happen in Safari (both desktop and mobile) - you will instead get a js error which doesn't allow the script to continue normally, so you don't get the alert (and all the other important code in real usage).

Please let me know if you have any ideas or if you think that this is a too weird edge case to deserve any attention.

Thanks!
Ruben.

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like the underlying cause is [WebKit bug 134765](https://bugs.webkit.org/show_bug.cgi?id=134765).

Which means we'll have to hack a solution. I recommend making the special item element 100%, and using an additional inner content element with the calc value for 100vw width. See CodePen http://codepen.io/desandro/pen/be5367e80371473e85eff0dc72429c35/?editors=1111

``` html
  <div class="grid-item grid-item--special">
    <div class="special-content"></div>
  </div>
```

``` css
.grid-item--special {
  width: 100%;
  margin: 10px 0;
  border: none;
}

.special-content {
  position: absolute;
  left: calc((((100vw - 100%) / 2) * -1));
  border: 2px solid #333;
  width: 100vw;
  height: 100%;
  background: red;
}
```
