### ISSUE TITLE
how to make isotope working with various size of boxes

### ISSUE THREAD

**Issue by rae0724** [metafizzy/isotope#1189]
Hi I am new in isotope, and I faced a problem which I cant make the boxes displaying well as the image below.
https://i.stack.imgur.com/Z3w5S.jpg

I can't make the first 4 boxes in a row. and the rest two stay in a row.
Please help me.
Thank you.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by rae0724** [comment]
Hi, here's my codepen
http://codepen.io/rae0724/pen/woBEjj
however, i don't know what's wrong
am i using wrong layout?
I want it to be layout like the image as I stated earlier....

**Comment by desandro** [comment]
Looks like you need to set the width of `.grid-sizer` to a multiple of the columnWidth. Looking at your item widths:

``` css
.w1 { width: 55%; }
.w2 { width: 45%; }
.w3 { width: 40%; }
.w4 { width: 60%; }
```

`5%` would be the greatest common multiple.

``` css
.grid-sizer {
  width: 5%;
}
```

See demo http://codepen.io/desandro/pen/ec1dfa5ee1169369b2bc18d680a73178/
