### ISSUE TITLE
isotope not animating

### ISSUE THREAD

**Issue by to8gal** [metafizzy/isotope#1193]
I inserted all css3 style as instructed and set with Vanilla js animationEngine: 'css',

but still nothing happen.

I see also a : Bad element for isotope: null on the minified at 13261

but so far didn´t recognize any other problem except this

can this be related?

**Comment by to8gal** [comment]
I can write laso the js:

```
<script  type="text/javascript">
var elem = document.querySelector('.grid');
var iso = new Isotope( elem, {
  itemSelector: '.grid-item',
  masonry: {
  columnWidth: 50,
  gutter: 10
},
animationEngine: 'css',
transitionDuration: '0.8s'
});
</script>
```

the css:

```
* { box-sizing: border-box; }


/* ---- grid ---- */

.grid {
  
  max-width: 1200px;
}

/* clear fix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- .grid-item ---- */



.grid-item {
  float: left;
  width: 200px;
  height: 300px;
  margin:10px;
 
}

/*.grid-item::after {
  content: attr(alt);
}	*/

.grid-item a, .grid-item a img {
 
  width: 300px;
  height: 450px;
  line-height:100%;
  vertical-align:middle;
  text-align:center;
}

.grid,
.grid .grid-item {
  /* change duration value to whatever you like */
  -webkit-transition-duration: 0.8s;
     -moz-transition-duration: 0.8s;
      -ms-transition-duration: 0.8s;
       -o-transition-duration: 0.8s;
          transition-duration: 0.8s;
}

.grid {
  -webkit-transition-property: height, width;
     -moz-transition-property: height, width;
      -ms-transition-property: height, width;
       -o-transition-property: height, width;
          transition-property: height, width;
}

.grid .grid-item {
  -webkit-transition-property: -webkit-transform, opacity;
     -moz-transition-property:    -moz-transform, opacity;
      -ms-transition-property:     -ms-transform, opacity;
       -o-transition-property:      -o-transform, opacity;
          transition-property:         transform, opacity;
}

.grid-item-text {position:relative; top:-60%; color:#fff; width:50%; padding-left:25%; padding-right:25%; font-size:1.5em; font-weight:bold; vertical-align:middle; text-align:center;height: 15%;
overflow: hidden;	}

.grid-item.odd, .grid-item.odd a, .grid-item.odd a img { width: 150px;height: 225px; }
.grid-item.even, .grid-item.even a, .grid-item.even a img { width: 200px;height: 300px; }
.grid-item.odd.even, .grid-item.odd.even a, .grid-item.odd.even a img { width: 100px;height: 150px; }

 @media only screen and (max-width:960px) {
	 
.grid-item.odd, .grid-item.odd a, .grid-item.odd a img { width: 300px;height: 450px; }
.grid-item.even, .grid-item.even a, .grid-item.even a img { width: 300px;height: 450px; }
.grid-item.odd.even, .grid-item.odd.even a, .grid-item.odd.even a img { width: 300px;height: 450px; }
 }


```

and the HTML (more or less):

```
<div class="grid">
   
<div class="grid-item even" alt="alt="...">
                       <a href="..." title="..." class="..."><img src="....jpg" alt="...."></a>
</div> 
<div class="grid-item odd even" alt="...">
                       <a href="..." title="..." class="..."><img src="....jpg" alt="...."></a>
</div>
 <div class="grid-item even" alt="...">
                       <a href="..." title="..." class="..."><img src="....jpg" alt="...."></a>
</div>      <div class="grid-item odd" alt="...">
                        <a href="..." title="..." class="..."><img src="....jpg" alt="...."></a>
</div>    <div class="grid-item even" alt="...">
                       <a href="..." title="..." class="..."><img src="....jpg" alt="...."></a>
</div>       <div class="grid-item last odd even" alt="...">
                        <a href="..." title="..." class="..."><img src="....jpg" alt="...."></a>
</div>
           

</div>
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by to8gal** [comment]
sure is basically already there, I actually tried on codepen and all is working,

dunno then, related to the Bad element for isotope: null on line 13261?

[codepen](https://codepen.io/to8gal/pen/JbbRxM)

**Comment by desandro** [comment]
Looks like you have some leftover CSS properties from Isotope v1. You can remove the CSS transition properties.

``` css
.grid,
.grid .grid-item {
  /* change duration value to whatever you like */
  -webkit-transition-duration: 0.8s;
     -moz-transition-duration: 0.8s;
      -ms-transition-duration: 0.8s;
       -o-transition-duration: 0.8s;
          transition-duration: 0.8s;
}

.grid {
  -webkit-transition-property: height, width;
     -moz-transition-property: height, width;
      -ms-transition-property: height, width;
       -o-transition-property: height, width;
          transition-property: height, width;
}

.grid .grid-item {
  -webkit-transition-property: -webkit-transform, opacity;
     -moz-transition-property:    -moz-transform, opacity;
      -ms-transition-property:     -ms-transform, opacity;
       -o-transition-property:      -o-transform, opacity;
          transition-property:         transform, opacity;
}
```

See demo https://codepen.io/desandro/pen/75cb167071163a05f607f91ef693057e/
