### ISSUE TITLE
On window resize item not changed as mansory 

### ISSUE THREAD

**Issue by pankajxenix** [metafizzy/isotope#1463]
Hi,

Thankyou for great plugin . I use this example in my site https://codepen.io/desandro/pen/NqNBxy
 This is working fine as demo. But I have one issue . When I resize window It always show three coloum. Please let me know why this not work as normal isotop ?

Thankyou

**Comment by pankajxenix** [comment]
If you check this codepen demo https://codepen.io/desandro/pen/NqNBxy . You see it always show three items . If my screen size is small but it always show three .

**Comment by desandro** [comment]
That demo uses percents for item width:

``` css
.grid-sizer,
.grid-item {
  width: 33.333%;
}
```

You can also use fixed sizes. See https://codepen.io/desandro/pen/osFxj

``` css
.grid-item {
  width: 160px;
}
```
