### ISSUE TITLE
Allow sort direction toggle on click

### ISSUE THREAD

**Issue by circlecube** [metafizzy/isotope#202]
I've figured out a way to allow the sort buttons to be clickable to toggle between ascending and descending sorting for the specific element, as well as some simple css to add indicators:

``` javascript
//javascript - altering sort example function 
$optionLinks.click(function(){
      var $this = $(this);
      // don't proceed if already selected
      if ( $this.hasClass('selected') ) {
        if ($this.hasClass('asc')){
          $this.removeClass('asc').addClass('desc');
        }
        else {
          $this.removeClass('desc').addClass('asc');
        }
      }
      var $optionSet = $this.parents('.option-set');
      $optionSet.find('.selected').removeClass('selected');
      $this.addClass('selected');

      // make option object dynamically, i.e. { filter: '.my-filter-class' }
      var options = {},
          key = $optionSet.attr('data-option-key'),
          value = $this.attr('data-option-value');
      // parse 'false' as false boolean
      value = value === 'false' ? false : value;
      options[ key ] = value;
      options[ 'sortAscending' ] = $this.hasClass('asc');
      if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
        // changes in layout modes need extra logic
        changeLayoutMode( $this, options )
      } else {
        // otherwise, apply new options
        $containter.isotope( options );
      }

      return false;
    });
```

``` css
//add indicator for asc and desc sorting
#options ul li a.selected.asc:after { content: ' ▲'; line-height: 150%; font-size: 50%; color: rgba(255,255,255,.5); }
#options ul li a.selected.desc:after { content: ' ▼'; line-height: 150%; font-size: 50%; color: rgba(255,255,255,.5); }
```

Then in the html just add the initial class to the sorting option, either (asc, desc).
