### ISSUE TITLE
Masonry Column Shift + Gutters Update

### ISSUE THREAD

**Issue by jamilabreu** [metafizzy/isotope#641]
I'm attempting to use Masonry Column Shift + Gutters via this gist:
https://gist.github.com/desandro/2624166

but it seems to not be recognizing the gutterWidth value:

```
$container.isotope
  itemSelector: '.user'
  masonry:
    columnWidth: 20
  masonryColumnShift:
    gutterWidth: 20
```

Code: http://jsfiddle.net/DQydj/331/
